// <auto-generated />
using System;
using EarlyBid.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EarlyBid.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190828171613_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EarlyBid.Shared.Models.Auction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Auction");
                });

            modelBuilder.Entity("EarlyBid.Shared.Models.Bid", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuctionId");

                    b.Property<string>("BidderNumber");

                    b.Property<DateTime>("Created");

                    b.Property<decimal>("EndPrice");

                    b.Property<decimal>("StartingPrice");

                    b.Property<string>("StickerNumber");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("EarlyBid.Shared.Models.Bid", b =>
                {
                    b.HasOne("EarlyBid.Shared.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId");
                });
#pragma warning restore 612, 618
        }
    }
}
